# Generated by Django 5.0.3 on 2024-04-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_inventario_carro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('barrio', models.CharField(max_length=255)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
